name: Run Python script and push changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
jobs:
  run_python_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Script
      env:
          THRD_PARS: '128'
          PARS_DP: '2'
          USE_INV_TC: 'n'
      run: |
        python tg-parser.py
          
    - name: Local Authentication
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
    - name: Commit & push
      run: |
        git add .
        git commit -m "Update files"
        git pull
        git push
